fixed ngif that was missing an asterisk: StaticInjectorError(AppModule)[NgIf -> TemplateRef]
there should be a test to check for this.
resolved the following error:
StaticInjectorError(AppModule)[NgIf -> TemplateRef]:
  StaticInjectorError(Platform: core)[NgIf -> TemplateRef]:
    NullInjectorError: No provider for TemplateRef!